server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: "yourdoctor.noreply@gmail.com"
    password: "TwojDoktor1234"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

##########JWT##########
jwt:
  expirationTime: 3600000
  secret: 29t7syadgf87qtr92rgu8yofvdc8023tr2379rfvcusav82t92